### ISSUE TITLE
get an object returned when I print (uk_stocks)

### ISSUE THREAD

**Issue by geofffoster** [portfolioplus/pytickersymbols#34]
using the examples I can print stock_data, countries etc. 

For the second example when 
from pytickersymbols import PyTickerSymbols
uk_stocks = stock_data.get_stocks_by_index('FTSE 100')
print(uk_stocks)

 I get <filter object at 0x7fbd543e8048> 

I was expecting a list of tickers for the FTSE 100

**Comment by SlashGordon** [comment]
Please try:

`print(list(uk_stocks))`
