### ISSUE TITLE
Exchange Type

### ISSUE THREAD

**Issue by Costanza90** [portfolioplus/pytickersymbols#420]
Nice work! One question, though: How can I download the symbols for German stocks listed on XETRA instead of 'Frankfurt' (in this case the symbol output should be .DE instead of .F)?

**Comment by SlashGordon** [comment]
You should replace the sub strings as follows: `map(lambda x: x.replace('.F', '.DE'), stock_data.get_dax_frankfurt_yahoo_tickers())`
