### ISSUE TITLE
get_all_countries() is returning the cities [[Paris]] and [[Cleveland]]

### ISSUE THREAD

**Issue by peterjgithub** [portfolioplus/pytickersymbols#72]
I am new in programming, feel free to give feedback if his is not the most appropriate way to post this question.

get_all_countries() is returning the cities [[Paris]] and [[Cleveland]] and also 'en'
Is that the purpose? 

FYI 

=> get_all_countries():
['', 'Isle of Man', 'en', 'China', 'France', 'Luxembourg', 'Bermuda', 'Russia', '[[Paris]]', 'South Africa', 'Spain', 'United States', 'Mexico', 'Argentina', 'Sweden', 'Czechia', 'Australia', 'Italy', '[[Cleveland]]', 'Austria', 'Netherlands', 'Canada', 'United Kingdom', 'Switzerland', 'Belgium', 'Israel', 'Germany', 'Russian Federation', 'Ireland', 'Finland']

=> get_stocks_by_country('en'):
{'name': 'Dow Inc.', 'wiki_name': 'Dow Inc.', 'symbol': 'DOW', 'country': 'en', 'indices': ['DOW JONES', 'S&P 100', 'S&P 500'], 'industries': ['Chemicals'], 'symbols': [{'yahoo': 'DOW', 'google': 'NYSE:DOW', 'currency': 'USD'}], 'isins': [], 'metadata': {'founded': 2019, 'employees': 36500}, 'id': 1001}

=> get_stocks_by_country('[[Paris]]'):
{'name': 'Ipsos SA', 'wiki_name': 'Ipsos SA', 'symbol': 'IPZ', 'country': '[[Paris]]', 'indices': ['CAC Mid 60'], 'industries': ['Public opinion research'], 'symbols': [{'yahoo': 'IPZ.F', 'google': 'FRA:IPZ', 'currency': 'EUR'}], 'isins': ['FR0000073298'], 'metadata': {'founded': 1975, 'employees': 16664}, 'id': 1082}

=> get_stocks_by_country('[[Cleveland]]'):
{'name': 'KeyBank', 'wiki_name': 'KeyBank', 'symbol': 'KEY', 'country': '[[Cleveland]]', 'indices': ['S&P 500'], 'industries': ['Financial services'], 'symbols': [{'yahoo': 'KEY', 'google': 'NYSE:KEY', 'currency': 'USD'}], 'isins': [], 'metadata': {'founded': 1825, 'employees': 17999}, 'id': 1008}

=> get_stocks_by_country(''):
These countries seem to have no country? just check if that is correct?

{'name': 'Norfolk Southern Corp.', 'wiki_name': 'Norfolk Southern Corp.', 'symbol': 'NSC', 'country': '', 'indices': ['S&P 500'], 'industries': [], 'symbols': [], 'isins': [], 'metadata': {'founded': 0, 'employees': 0}, 'id': 1018}

{'name': 'Pool Corporation', 'wiki_name': 'Pool Corporation', 'symbol': 'POOL', 'country': '', 'indices': ['S&P 500'], 'industries': [], 'symbols': [], 'isins': [], 'metadata': {'founded': 0, 'employees': 0}, 'id': 1026}

{'name': 'IMCD', 'wiki_name': 'IMCD', 'symbol': 'IMCD', 'country': '', 'indices': ['AEX'], 'industries': [], 'symbols': [], 'isins': [], 'metadata': {'founded': 0, 'employees': 0}, 'id': 1049}

{'name': 'DBV Technologies', 'wiki_name': 'DBV Technologies', 'symbol': 'DBVT', 'country': '', 'indices': ['CAC Mid 60'], 'industries': [], 'symbols': [{'yahoo': 'DBVT', 'google': 'NASDAQ:DBVT', 'currency': 'USD'}, {'yahoo': 'DBVA.F', 'google': 'FRA:DBVA', 'currency': 'EUR'}], 'isins': [], 'metadata': {'founded': 0, 'employees': 0}, 'id': 1065}

{'name': 'Elior Group', 'wiki_name': 'Elior Group', 'symbol': '21E', 'country': '', 'indices': ['CAC Mid 60'], 'industries': [], 'symbols': [{'yahoo': '21E.F', 'google': 'FRA:21E', 'currency': 'EUR'}], 'isins': [], 'metadata': {'founded': 0, 'employees': 0}, 'id': 1066}

{'name': 'Genfit', 'wiki_name': 'Genfit', 'symbol': 'XUP', 'country': '', 'indices': ['CAC Mid 60'], 'industries': [], 'symbols': [{'yahoo': 'XUP.F', 'google': 'FRA:XUP', 'currency': 'EUR'}, {'yahoo': 'GNFTF', 'google': 'OTCMKTS:GNFTF', 'currency': 'USD'}, {'yahoo': 'GNFT', 'google': 'NASDAQ:GNFT', 'currency': 'USD'}, {'yahoo': 'XUPB.F', 'google': 'FRA:XUPB', 'currency': 'EUR'}], 'isins': [], 'metadata': {'founded': 0, 'employees': 0}, 'id': 1076}

{'name': 'Gaztransport & Technigaz', 'wiki_name': 'Gaztransport & Technigaz', 'symbol': '9TG', 'country': '', 'indices': ['CAC Mid 60'], 'industries': [], 'symbols': [{'yahoo': '9TG.F', 'google': 'FRA:9TG', 'currency': 'EUR'}], 'isins': [], 'metadata': {'founded': 0, 'employees': 0}, 'id': 1077}

{'name': 'Mercialys', 'wiki_name': 'Mercialys', 'symbol': 'MEIYF', 'country': '', 'indices': ['CAC Mid 60'], 'industries': [], 'symbols': [{'yahoo': 'MEIYF', 'google': 'OTCMKTS:MEIYF', 'currency': 'USD'}, {'yahoo': 'M8Y.F', 'google': 'FRA:M8Y', 'currency': 'EUR'}], 'isins': [], 'metadata': {'founded': 0, 'employees': 0}, 'id': 1087}

{'name': 'TF1 Group', 'wiki_name': 'TF1 Group', 'symbol': None, 'country': '', 'indices': ['CAC Mid 60'], 'industries': [], 'symbols': [], 'isins': [], 'metadata': {'founded': 0, 'employees': 0}, 'id': 1101}

{'name': 'Virbac', 'wiki_name': 'Virbac', 'symbol': 'VRBCF', 'country': '', 'indices': ['CAC Mid 60'], 'industries': [], 'symbols': [{'yahoo': 'VRBCF', 'google': 'OTCMKTS:VRBCF', 'currency': 'USD'}, {'yahoo': 'V16.F', 'google': 'FRA:V16', 'currency': 'EUR'}], 'isins': [], 'metadata': {'founded': 0, 'employees': 0}, 'id': 1105}

{'name': 'Aedifica', 'wiki_name': 'Aedifica', 'symbol': None, 'country': '', 'indices': ['BEL 20'], 'industries': [], 'symbols': [], 'isins': [], 'metadata': {'founded': 0, 'employees': 0}, 'id': 1114}

{'name': 'WDP', 'wiki_name': 'WDP', 'symbol': None, 'country': '', 'indices': ['BEL 20'], 'industries': [], 'symbols': [], 'isins': [], 'metadata': {'founded': 0, 'employees': 0}, 'id': 1120}

{'name': 'Kojamo', 'wiki_name': 'Kojamo', 'symbol': 'KOJAMO', 'country': '', 'indices': ['OMX Helsinki 25'], 'industries': [], 'symbols': [{'yahoo': 'V4OC.F', 'google': 'FRA:V4OC', 'currency': 'EUR'}], 'isins': [], 'metadata': {'founded': 0, 'employees': 0}, 'id': 1127}

{'name': 'TCS Group', 'wiki_name': 'TCS Group', 'symbol': None, 'country': '', 'indices': ['MOEX'], 'industries': [], 'symbols': [], 'isins': [], 'metadata': {'founded': 0, 'employees': 0}, 'id': 1172}

**Comment by SlashGordon** [comment]
Thank you for the message. Please check the next release.
