### ISSUE TITLE
Accessing other indices

### ISSUE THREAD

**Issue by HangryBear** [portfolioplus/pytickersymbols#80]
How do I access other indices that aren't in the list, for example the UK AIM 100? Thank you.

**Comment by SlashGordon** [comment]
I don't know the UK AIM 100, do you mean the FTSE 100?

**Comment by HangryBear** [comment]
No, I do not. This is the Alternative Investment Market, it's basically
small caps on the FTSE, they have their own index:
https://en.wikipedia.org/wiki/FTSE_AIM_100_Index#:~:text=The%20FTSE%20AIM%20UK%20100,Alternative%20Investment%20Market%20(AIM)
.

**Comment by ersineser** [comment]
Hello, 
How do i access Borsa Istanbul (Turkey) BIST symbols/stock list and historical data.
Example Stock : https://finance.yahoo.com/quote/KCHOL.IS
Thank you.

**Comment by ersineser** [comment]
> Hello, How do i access Borsa Istanbul (Turkey) BIST symbols/stock list and historical data. Example Stock : https://finance.yahoo.com/quote/KCHOL.IS Thank you.

are there any help?
