### ISSUE TITLE
Update cycle of the `stocks.yaml`

### ISSUE THREAD

**Issue by philippschmalen** [portfolioplus/pytickersymbols#87]
Moin!

First of all, I love your work. It saves me tons of time, many thanks for putting this out!

My question is about the `stocks.yaml` file. As far as I understood your implementation, this is where all stock information is loaded from. But **how often is it updated?** Or how is it generally assured to query the most up-to-date stock info?

Thanks a bunch!
All the best from Berlin

**Comment by SlashGordon** [comment]
Hi Philipp,

We have an update job, the scanner checks wiki tables for updates and synchronizes the new stuff with our database.  The job has stopped working and I will fix it when I have time for it.  The update cycle should be done once a week.

I will close the issue when I fix the update job.

Best

Slash

**Comment by philippschmalen** [comment]
Thanks for reaching out and all the details. Great that you are on it! 
Looking forward that it gets updated recently. Recent fundamental data makes pytickersymbols valuable!

**Comment by SlashGordon** [comment]
Hello Philipp, 

the update job is working now and is scheduled once a week.

Best slash
